/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryV2RouteImport } from './routes/library-v2'
import { Route as SplatRouteImport } from './routes/$'
import { Route as WishlistRouteRouteImport } from './routes/wishlist/route'
import { Route as WatchlistRouteRouteImport } from './routes/watchlist/route'
import { Route as ToolsRouteRouteImport } from './routes/tools/route'
import { Route as SyncRouteRouteImport } from './routes/sync/route'
import { Route as StatsRouteRouteImport } from './routes/stats/route'
import { Route as SearchRouteRouteImport } from './routes/search/route'
import { Route as PlaylistExplorerRouteRouteImport } from './routes/playlist-explorer/route'
import { Route as LibraryRouteRouteImport } from './routes/library/route'
import { Route as IssuesRouteRouteImport } from './routes/issues/route'
import { Route as ImportRouteRouteImport } from './routes/import/route'
import { Route as DiscoverRouteRouteImport } from './routes/discover/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AutomationsRouteRouteImport } from './routes/automations/route'
import { Route as ActiveDownloadsRouteRouteImport } from './routes/active-downloads/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportIndexRouteImport } from './routes/import/index'
import { Route as LabelDetailIdRouteImport } from './routes/label-detail/$id'
import { Route as ImportSinglesRouteImport } from './routes/import/singles'
import { Route as ImportAutoRouteImport } from './routes/import/auto'
import { Route as ImportAlbumRouteImport } from './routes/import/album'
import { Route as ArtistDetailSourceIdRouteImport } from './routes/artist-detail/$source/$id'

const LibraryV2Route = LibraryV2RouteImport.update({
  id: '/library-v2',
  path: '/library-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRouteRoute = WishlistRouteRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRouteRoute = WatchlistRouteRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRouteRoute = SyncRouteRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRouteRoute = StatsRouteRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRouteRoute = SearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistExplorerRouteRoute = PlaylistExplorerRouteRouteImport.update({
  id: '/playlist-explorer',
  path: '/playlist-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRouteRoute = LibraryRouteRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRouteRoute = IssuesRouteRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRouteRoute = ImportRouteRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRouteRoute = DiscoverRouteRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRouteRoute = AutomationsRouteRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveDownloadsRouteRoute = ActiveDownloadsRouteRouteImport.update({
  id: '/active-downloads',
  path: '/active-downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportRouteRoute,
} as any)
const LabelDetailIdRoute = LabelDetailIdRouteImport.update({
  id: '/label-detail/$id',
  path: '/label-detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportSinglesRoute = ImportSinglesRouteImport.update({
  id: '/singles',
  path: '/singles',
  getParentRoute: () => ImportRouteRoute,
} as any)
const ImportAutoRoute = ImportAutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => ImportRouteRoute,
} as any)
const ImportAlbumRoute = ImportAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => ImportRouteRoute,
} as any)
const ArtistDetailSourceIdRoute = ArtistDetailSourceIdRouteImport.update({
  id: '/artist-detail/$source/$id',
  path: '/artist-detail/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-downloads': typeof ActiveDownloadsRouteRoute
  '/automations': typeof AutomationsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/discover': typeof DiscoverRouteRoute
  '/import': typeof ImportRouteRouteWithChildren
  '/issues': typeof IssuesRouteRoute
  '/library': typeof LibraryRouteRoute
  '/playlist-explorer': typeof PlaylistExplorerRouteRoute
  '/search': typeof SearchRouteRoute
  '/stats': typeof StatsRouteRoute
  '/sync': typeof SyncRouteRoute
  '/tools': typeof ToolsRouteRoute
  '/watchlist': typeof WatchlistRouteRoute
  '/wishlist': typeof WishlistRouteRoute
  '/$': typeof SplatRoute
  '/library-v2': typeof LibraryV2Route
  '/import/album': typeof ImportAlbumRoute
  '/import/auto': typeof ImportAutoRoute
  '/import/singles': typeof ImportSinglesRoute
  '/label-detail/$id': typeof LabelDetailIdRoute
  '/import/': typeof ImportIndexRoute
  '/artist-detail/$source/$id': typeof ArtistDetailSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-downloads': typeof ActiveDownloadsRouteRoute
  '/automations': typeof AutomationsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/discover': typeof DiscoverRouteRoute
  '/issues': typeof IssuesRouteRoute
  '/library': typeof LibraryRouteRoute
  '/playlist-explorer': typeof PlaylistExplorerRouteRoute
  '/search': typeof SearchRouteRoute
  '/stats': typeof StatsRouteRoute
  '/sync': typeof SyncRouteRoute
  '/tools': typeof ToolsRouteRoute
  '/watchlist': typeof WatchlistRouteRoute
  '/wishlist': typeof WishlistRouteRoute
  '/$': typeof SplatRoute
  '/library-v2': typeof LibraryV2Route
  '/import/album': typeof ImportAlbumRoute
  '/import/auto': typeof ImportAutoRoute
  '/import/singles': typeof ImportSinglesRoute
  '/label-detail/$id': typeof LabelDetailIdRoute
  '/import': typeof ImportIndexRoute
  '/artist-detail/$source/$id': typeof ArtistDetailSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-downloads': typeof ActiveDownloadsRouteRoute
  '/automations': typeof AutomationsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/discover': typeof DiscoverRouteRoute
  '/import': typeof ImportRouteRouteWithChildren
  '/issues': typeof IssuesRouteRoute
  '/library': typeof LibraryRouteRoute
  '/playlist-explorer': typeof PlaylistExplorerRouteRoute
  '/search': typeof SearchRouteRoute
  '/stats': typeof StatsRouteRoute
  '/sync': typeof SyncRouteRoute
  '/tools': typeof ToolsRouteRoute
  '/watchlist': typeof WatchlistRouteRoute
  '/wishlist': typeof WishlistRouteRoute
  '/$': typeof SplatRoute
  '/library-v2': typeof LibraryV2Route
  '/import/album': typeof ImportAlbumRoute
  '/import/auto': typeof ImportAutoRoute
  '/import/singles': typeof ImportSinglesRoute
  '/label-detail/$id': typeof LabelDetailIdRoute
  '/import/': typeof ImportIndexRoute
  '/artist-detail/$source/$id': typeof ArtistDetailSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-downloads'
    | '/automations'
    | '/dashboard'
    | '/discover'
    | '/import'
    | '/issues'
    | '/library'
    | '/playlist-explorer'
    | '/search'
    | '/stats'
    | '/sync'
    | '/tools'
    | '/watchlist'
    | '/wishlist'
    | '/$'
    | '/library-v2'
    | '/import/album'
    | '/import/auto'
    | '/import/singles'
    | '/label-detail/$id'
    | '/import/'
    | '/artist-detail/$source/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-downloads'
    | '/automations'
    | '/dashboard'
    | '/discover'
    | '/issues'
    | '/library'
    | '/playlist-explorer'
    | '/search'
    | '/stats'
    | '/sync'
    | '/tools'
    | '/watchlist'
    | '/wishlist'
    | '/$'
    | '/library-v2'
    | '/import/album'
    | '/import/auto'
    | '/import/singles'
    | '/label-detail/$id'
    | '/import'
    | '/artist-detail/$source/$id'
  id:
    | '__root__'
    | '/'
    | '/active-downloads'
    | '/automations'
    | '/dashboard'
    | '/discover'
    | '/import'
    | '/issues'
    | '/library'
    | '/playlist-explorer'
    | '/search'
    | '/stats'
    | '/sync'
    | '/tools'
    | '/watchlist'
    | '/wishlist'
    | '/$'
    | '/library-v2'
    | '/import/album'
    | '/import/auto'
    | '/import/singles'
    | '/label-detail/$id'
    | '/import/'
    | '/artist-detail/$source/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveDownloadsRouteRoute: typeof ActiveDownloadsRouteRoute
  AutomationsRouteRoute: typeof AutomationsRouteRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  DiscoverRouteRoute: typeof DiscoverRouteRoute
  ImportRouteRoute: typeof ImportRouteRouteWithChildren
  IssuesRouteRoute: typeof IssuesRouteRoute
  LibraryRouteRoute: typeof LibraryRouteRoute
  PlaylistExplorerRouteRoute: typeof PlaylistExplorerRouteRoute
  SearchRouteRoute: typeof SearchRouteRoute
  StatsRouteRoute: typeof StatsRouteRoute
  SyncRouteRoute: typeof SyncRouteRoute
  ToolsRouteRoute: typeof ToolsRouteRoute
  WatchlistRouteRoute: typeof WatchlistRouteRoute
  WishlistRouteRoute: typeof WishlistRouteRoute
  SplatRoute: typeof SplatRoute
  LibraryV2Route: typeof LibraryV2Route
  LabelDetailIdRoute: typeof LabelDetailIdRoute
  ArtistDetailSourceIdRoute: typeof ArtistDetailSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library-v2': {
      id: '/library-v2'
      path: '/library-v2'
      fullPath: '/library-v2'
      preLoaderRoute: typeof LibraryV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist-explorer': {
      id: '/playlist-explorer'
      path: '/playlist-explorer'
      fullPath: '/playlist-explorer'
      preLoaderRoute: typeof PlaylistExplorerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-downloads': {
      id: '/active-downloads'
      path: '/active-downloads'
      fullPath: '/active-downloads'
      preLoaderRoute: typeof ActiveDownloadsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/label-detail/$id': {
      id: '/label-detail/$id'
      path: '/label-detail/$id'
      fullPath: '/label-detail/$id'
      preLoaderRoute: typeof LabelDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/singles': {
      id: '/import/singles'
      path: '/singles'
      fullPath: '/import/singles'
      preLoaderRoute: typeof ImportSinglesRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/import/auto': {
      id: '/import/auto'
      path: '/auto'
      fullPath: '/import/auto'
      preLoaderRoute: typeof ImportAutoRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/import/album': {
      id: '/import/album'
      path: '/album'
      fullPath: '/import/album'
      preLoaderRoute: typeof ImportAlbumRouteImport
      parentRoute: typeof ImportRouteRoute
    }
    '/artist-detail/$source/$id': {
      id: '/artist-detail/$source/$id'
      path: '/artist-detail/$source/$id'
      fullPath: '/artist-detail/$source/$id'
      preLoaderRoute: typeof ArtistDetailSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ImportRouteRouteChildren {
  ImportAlbumRoute: typeof ImportAlbumRoute
  ImportAutoRoute: typeof ImportAutoRoute
  ImportSinglesRoute: typeof ImportSinglesRoute
  ImportIndexRoute: typeof ImportIndexRoute
}

const ImportRouteRouteChildren: ImportRouteRouteChildren = {
  ImportAlbumRoute: ImportAlbumRoute,
  ImportAutoRoute: ImportAutoRoute,
  ImportSinglesRoute: ImportSinglesRoute,
  ImportIndexRoute: ImportIndexRoute,
}

const ImportRouteRouteWithChildren = ImportRouteRoute._addFileChildren(
  ImportRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveDownloadsRouteRoute: ActiveDownloadsRouteRoute,
  AutomationsRouteRoute: AutomationsRouteRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  DiscoverRouteRoute: DiscoverRouteRoute,
  ImportRouteRoute: ImportRouteRouteWithChildren,
  IssuesRouteRoute: IssuesRouteRoute,
  LibraryRouteRoute: LibraryRouteRoute,
  PlaylistExplorerRouteRoute: PlaylistExplorerRouteRoute,
  SearchRouteRoute: SearchRouteRoute,
  StatsRouteRoute: StatsRouteRoute,
  SyncRouteRoute: SyncRouteRoute,
  ToolsRouteRoute: ToolsRouteRoute,
  WatchlistRouteRoute: WatchlistRouteRoute,
  WishlistRouteRoute: WishlistRouteRoute,
  SplatRoute: SplatRoute,
  LibraryV2Route: LibraryV2Route,
  LabelDetailIdRoute: LabelDetailIdRoute,
  ArtistDetailSourceIdRoute: ArtistDetailSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
